// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

/// Quality selection mode for video playback.
typedef NS_ENUM(NSUInteger, FVPPlatformQualitySelectionMode) {
  /// Automatic quality selection (adaptive bitrate).
  FVPPlatformQualitySelectionModeAuto = 0,
  /// Manual quality selection (locked to specific quality).
  FVPPlatformQualitySelectionModeManual = 1,
};

/// Wrapper for FVPPlatformQualitySelectionMode to allow for nullability.
@interface FVPPlatformQualitySelectionModeBox : NSObject
@property(nonatomic, assign) FVPPlatformQualitySelectionMode value;
- (instancetype)initWithValue:(FVPPlatformQualitySelectionMode)value;
@end

/// Events sent from the platform to Flutter.
typedef NS_ENUM(NSUInteger, FVPVideoEvent) {
  /// The player has initialized.
  FVPVideoEventInitialized = 0,
  /// The video completed playback.
  FVPVideoEventCompleted = 1,
  /// The player started buffering.
  FVPVideoEventBufferingStart = 2,
  /// The player ended buffering.
  FVPVideoEventBufferingEnd = 3,
  /// The buffered regions changed.
  FVPVideoEventBufferingUpdate = 4,
  /// The player is playing changed.
  FVPVideoEventIsPlayingChanged = 5,
  /// An error occurred.
  FVPVideoEventError = 6,
  /// User requested next track via remote control.
  FVPVideoEventNextTrackRequested = 7,
  /// User requested previous track via remote control.
  FVPVideoEventPreviousTrackRequested = 8,
};

/// Wrapper for FVPVideoEvent to allow for nullability.
@interface FVPVideoEventBox : NSObject
@property(nonatomic, assign) FVPVideoEvent value;
- (instancetype)initWithValue:(FVPVideoEvent)value;
@end

@class FVPPlatformVideoViewCreationParams;
@class FVPCreationOptions;
@class FVPPlatformVideoQuality;
@class FVPNowPlayingMetadata;
@class FVPTexturePlayerIds;

/// Information passed to the platform view creation.
@interface FVPPlatformVideoViewCreationParams : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithPlayerId:(NSInteger )playerId;
@property(nonatomic, assign) NSInteger  playerId;
@end

@interface FVPCreationOptions : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithUri:(NSString *)uri
    httpHeaders:(NSDictionary<NSString *, NSString *> *)httpHeaders;
@property(nonatomic, copy) NSString * uri;
@property(nonatomic, copy) NSDictionary<NSString *, NSString *> * httpHeaders;
@end

/// Represents a video quality option (variant) in an HLS stream.
@interface FVPPlatformVideoQuality : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id
    width:(NSInteger )width
    height:(NSInteger )height
    bitrate:(NSInteger )bitrate
    isSelected:(BOOL )isSelected
    label:(nullable NSString *)label;
/// Unique identifier for the quality option (variant URL for iOS).
@property(nonatomic, copy) NSString * id;
/// Width of the video in pixels.
@property(nonatomic, assign) NSInteger  width;
/// Height of the video in pixels.
@property(nonatomic, assign) NSInteger  height;
/// Bitrate of the video in bits per second.
@property(nonatomic, assign) NSInteger  bitrate;
/// Whether this quality option is currently selected.
@property(nonatomic, assign) BOOL  isSelected;
/// Human-readable label for the quality option (e.g., "1080p").
@property(nonatomic, copy, nullable) NSString * label;
@end

/// Metadata for Now Playing Info (lock screen / control center).
@interface FVPNowPlayingMetadata : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithTitle:(nullable NSString *)title
    artist:(nullable NSString *)artist
    album:(nullable NSString *)album
    artworkUrl:(nullable NSString *)artworkUrl
    isLiveStream:(BOOL )isLiveStream;
@property(nonatomic, copy, nullable) NSString * title;
@property(nonatomic, copy, nullable) NSString * artist;
@property(nonatomic, copy, nullable) NSString * album;
@property(nonatomic, copy, nullable) NSString * artworkUrl;
@property(nonatomic, assign) BOOL  isLiveStream;
@end

@interface FVPTexturePlayerIds : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithPlayerId:(NSInteger )playerId
    textureId:(NSInteger )textureId;
@property(nonatomic, assign) NSInteger  playerId;
@property(nonatomic, assign) NSInteger  textureId;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *FVPGetMessagesCodec(void);

@protocol FVPAVFoundationVideoPlayerApi
- (void)initialize:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)createPlatformViewPlayerWithOptions:(FVPCreationOptions *)params error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable FVPTexturePlayerIds *)createTexturePlayerWithOptions:(FVPCreationOptions *)creationOptions error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setMixWithOthers:(BOOL)mixWithOthers error:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSString *)fileURLForAssetWithName:(NSString *)asset package:(nullable NSString *)package error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpFVPAVFoundationVideoPlayerApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FVPAVFoundationVideoPlayerApi> *_Nullable api);

extern void SetUpFVPAVFoundationVideoPlayerApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FVPAVFoundationVideoPlayerApi> *_Nullable api, NSString *messageChannelSuffix);


@protocol FVPVideoPlayerInstanceApi
- (void)setLooping:(BOOL)looping error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setVolume:(double)volume error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setPlaybackSpeed:(double)speed error:(FlutterError *_Nullable *_Nonnull)error;
- (void)playWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)position:(FlutterError *_Nullable *_Nonnull)error;
- (void)seekTo:(NSInteger)position completion:(void (^)(FlutterError *_Nullable))completion;
- (void)pauseWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)disposeWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Sets metadata for the Now Playing Info Center (lock screen / control center).
/// Only available on iOS.
- (void)setNowPlayingMetadata:(FVPNowPlayingMetadata *)metadata error:(FlutterError *_Nullable *_Nonnull)error;
/// Clears the Now Playing Info Center and deactivates the audio session.
/// Only available on iOS.
- (void)clearNowPlayingMetadata:(FlutterError *_Nullable *_Nonnull)error;
/// Gets the available video quality options for the current HLS stream.
///
/// Returns a list of available quality variants parsed from the HLS master
/// playlist. For non-HLS streams, returns an empty list.
///
/// @return `nil` only when `error != nil`.
- (nullable NSArray<FVPPlatformVideoQuality *> *)getVideoQualities:(FlutterError *_Nullable *_Nonnull)error;
/// Selects a specific video quality for playback.
///
/// Pass [qualityId] (variant URL) to select that quality.
/// Pass null to switch back to automatic quality selection (master playlist).
- (void)selectVideoQuality:(nullable NSString *)qualityId error:(FlutterError *_Nullable *_Nonnull)error;
/// Gets the current quality selection mode.
///
/// @return `nil` only when `error != nil`.
- (FVPPlatformQualitySelectionModeBox *_Nullable)getQualitySelectionMode:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpFVPVideoPlayerInstanceApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FVPVideoPlayerInstanceApi> *_Nullable api);

extern void SetUpFVPVideoPlayerInstanceApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FVPVideoPlayerInstanceApi> *_Nullable api, NSString *messageChannelSuffix);


@interface FVPVideoPlayerEventApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
/// Called when a video event occurs.
- (void)onVideoEventPlayerId:(NSInteger)playerId event:(FVPVideoEvent)event data:(NSDictionary<NSString *, id> *)data completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
